server:
  port: 8072
spring:
  application:
    name: gateway-server
  profiles:
    active: local
  config:
    import: "optional:configserver:${CONFIGSERVER_URI:http://localhost:8071}"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.example: DEBUG