spring:
  datasource:
    url: jdbc:postgresql://database:5432/ostock_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

encrypt:
  key: "IMSYMMETRIC"